#!/usr/bin/env python3
# Copyright (C) 2022
# ViliusSutkus89.com
# https://github.com/ViliusSutkus89/adbPullAs
#
# adbPullAs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import getopt
import os
import sys
from version import Versioner


if __name__ == '__main__':
    major = False
    minor = False
    patch = False
    try:
        opts, args = getopt.getopt(sys.argv[1:], '', ['major', 'minor', 'patch'])
        for o, a in opts:
            if o == '--major': major = True
            if o == '--minor': minor = True
            if o == '--patch': patch = True

    except getopt.GetoptError as err:
        print(err, file=sys.stderr)
        exit(os.EX_USAGE)

    versioner = Versioner()
    old_version = versioner.get_version_str()
    updated_file_list = []
    if major:
        updated_file_list = versioner.increment_major()
    elif minor:
        updated_file_list = versioner.increment_minor()
    elif patch:
        updated_file_list = versioner.increment_patch()
    else:
        print('Specify either --major, --minor or --patch', file=sys.stderr)
        exit(os.EX_USAGE)

    new_version = versioner.get_version_str()
    print(f'::set-output name=oldVersion::{old_version}')
    print(f'::set-output name=newVersion::{new_version}')

    updated_file_list = ' '.join(updated_file_list)
    print(f'::set-output name=files::{updated_file_list}')
